# Default platform pyproject.toml (x86, GB200, and any non-Jetson GPU)

[build-system]
requires = ["setuptools>=67", "wheel", "pip"]
build-backend = "setuptools.build_meta"

[project]
name = "gr00t"
version = "0.1.0"
requires-python = "==3.12.*"
dependencies = [
    "albumentations==1.4.18",
    "huggingface-hub[cli]",
    "opencv-python-headless>=4.5,<4.13",
    "av==16.1.0",
    "diffusers==0.35.1",
    "lmdb==1.7.5",
    "msgpack-numpy==0.4.8",
    "peft==0.17.1",
    "termcolor==3.2.0",
    "transformers==4.57.3",
    "tyro==0.9.17",
    "gitpython==3.1.46",
    "jsonlines==4.0.0",
    "gymnasium==1.2.2",
    "omegaconf==2.3.0",
    "torchcodec==0.4.0; platform_machine == 'x86_64'",
    "torchcodec==0.10.0a0; platform_machine == 'aarch64' and sys_platform == 'linux'",
    "wandb==0.23.0",
    "deepspeed==0.17.6; platform_machine != 'aarch64' or sys_platform != 'linux'",
    "triton==3.3.1; sys_platform == 'linux' and platform_machine == 'aarch64'",
    "tensorrt-cu12>=10.15.1.29; platform_machine == 'x86_64'",
    "tensorrt-cu13>=10.15.1.29; platform_machine == 'aarch64'",
]

[project.optional-dependencies]
dev = [
    "boto3",
    "ruff",
    "ipython",
    "pytest",
    "pytest-timeout",
    "build",
    "pre-commit",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["gr00t*"]

[tool.pytest.ini_options]
pythonpath = [".", "tests"]
addopts = "--import-mode=importlib"
markers = [
    "gpu: tests that require a GPU",
]

[tool.ruff]
line-length = 100
target-version = "py312"
src = ["gr00t"]
exclude = [
    "__pycache__",
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".vscode",
    ".venv",
    "dist",
    "logs",
    "*.ipynb",
    "external_dependencies",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.lint.isort]
case-sensitive = false
combine-as-imports = true
force-sort-within-sections = true
force-wrap-aliases = false
split-on-trailing-comma = false
lines-after-imports = 2
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

